version: "3.6"
services:

######## TEST @@@@@@@@@@@@@@@

  traefik:
    image: traefik:alpine
    container_name: traefik
    domainname: ${DOMAINNAME}
    hostname: traefik
#    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${USERDIR}/dockerha/uavtraefik:/etc/traefik
      - ${USERDIR}/dockerha/shared:/shared
      - ${USERDIR}/dockerha/cert:/cert
    command:
      - "--docker"
      - "--api"
      - "--logLevel=DEBUG"
      - "--debug=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


  whoami:
    image: containous/whoami
    container_name: whoami
    hostname: whoami
    domainname: ${DOMAINNAME}
#    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"



#Portainer - WebUI for Containers
  portainer:
    image: portainer/portainer
    container_name: portainer
    domainname: ${DOMAINNAME}
    hostname: portainer
#    restart: always
#    command: --no-auth
#    ports:
#      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/dockerha/uavportainer/data:/data
      - ${USERDIR}/dockerha/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


# Watchtower - Automatic Update of Containers/Apps
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    domainname: ${DOMAINNAME}
    hostname: watchtower
#    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


#Openssl - self signed certificates for Containers
  openssl:
    build:
      context: ${USERDIR}/dockerha/ #when alternative Dockerfile name used, context must be
      dockerfile: Dockerfile.openssl
    container_name: openssl
    domainname: ${DOMAINNAME}
    hostname: openssl
    volumes:
      - ${USERDIR}/dockerha/cert:/cert
      - ${USERDIR}/dockerha/shared/create-cert.sh:/shared/create-cert.sh
    command:
      - /bin/sh
      - create-cert.sh
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


######### FRONTENDS ##########

# Home Assistant - Smart Home Hub
  homeassistant:
    image: homeassistant/home-assistant
    container_name: homeassistant
    domainname: ${DOMAINNAME}
    hostname: homeassistant
#    restart: always
#    devices:
#      - /dev/ttyUSB0:/dev/ttyUSB0
#      - /dev/ttyUSB1:/dev/ttyUSB1
#      - /dev/ttyACM0:/dev/ttyACM0
    volumes:
      - ${USERDIR}/dockerha/uavha:/config
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/dockerha/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - influxdb
    labels:
      - "traefik.enable=false"


# NextCloud – Your Own Cloud Storage
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    domainname: ${DOMAINNAME}
    hostname: nextcloud
#      restart: always
    volumes:
      - ${USERDIR}/dockerha/uavnextcloud/data:/var/www/html
      - ${USERDIR}/dockerha/shared:/shared
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8081:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=false"


## phpMyAdmin - WebUI for MariaDB
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    container_name: phpmyadmin
#    domainname: ${DOMAINNAME}
#    hostname: phpmyadmin
##    restart: always
#    depends_on:
#      - mariadb
#    ports:
#      - "84:80"
#    environment:
#      - PMA_HOST=mariadb
#      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
#      - PUID=${PUID}
#      - PGID=${PGID}
#      - TZ=${TZ}
#    networks:
#      - ${NETWORK_NAME}
#    labels:
#      - "traefik.enable=false"



######### UTILITIES ##########

# MariaDB – Database Server for your NextCloud service
  mariadb:
    image: mariadb
    container_name: mariadb
    domainname: ${DOMAINNAME}
    hostname: mariadb
#    restart: always
    volumes:
      - ${USERDIR}/dockerha/uavmariadb/data:/var/lib/mysql
      - ${USERDIR}/dockerha/shared:/shared
      - /etc/localtime:/etc/localtime:ro
    command:
      - "--transaction-isolation=READ-COMMITTED" 
      - "--binlog-format=ROW"
#    ports:
#      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${NEXTCLOUD_DATABASE}
      - MYSQL_USER=${USER_NEXTCLOUD}
      - MYSQL_PASSWORD=${PASS_NEXTCLOUD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"



######### HOME ASSISTANT RELATED ##########

## NodeRed - Visualizing tasks
  nodered:
    build:
      context: ${USERDIR}/dockerha/ 
      dockerfile: Dockerfile.nodered
    container_name: node-red
    domainname: ${DOMAINNAME}
    hostname: nodered
#    restart: always
    depends_on:
      - homeassistant
    volumes:
      - ${USERDIR}/dockerha/uavnodered/data:/data
      - ${USERDIR}/dockerha/shared:/shared
#    ports:
#      - "1880:1880"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


## Mosquitto - MQTT broker 
  mosquitto:
    build:
      context: ${USERDIR}/dockerha/ 
      dockerfile: Dockerfile.mosquitto
    environment:
      - MOSQUITTO_USERNAME=${MOSQUITTO_USERNAME}
      - MOSQUITTO_PASSWORD=${MOSQUITTO_PASSWORD}
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    container_name: mosquitto
    domainname: ${DOMAINNAME}
    hostname: mosquitto
#    restart: on-failure
    depends_on:
      - homeassistant
    volumes:
      - ${USERDIR}/dockerha/uavmosquitto/config:/mosquitto/config
      - ${USERDIR}/dockerha/uavmosquitto/data:/mosquitto/data
      - ${USERDIR}/dockerha/uavmosquitto/log:/mosquitto/log
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


## TasmodaAdmin - Visual admin for Tasmoda devices
  tasmoadmin:
    image: raymondmm/tasmoadmin
    container_name: tasmoadmin
    domainname: ${DOMAINNAME}
    hostname: tasmoadmin
#    restart: always
    depends_on:
      - homeassistant
    volumes:
      - ${USERDIR}/dockerha/uavtasmoadmin/data:/data
      - ${USERDIR}/dockerha/uavtasmoadmin/log:/log
      - ${USERDIR}/dockerha/shared:/shared
    ports:
      - "88:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


## Grafana  - Graphical data  presentation
  grafana:
    build:
      context: ${USERDIR}/dockerha/
      dockerfile: Dockerfile.grafana
    container_name: grafana
    domainname: ${DOMAINNAME}
    hostname: grafana
#    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ${USERDIR}/dockerha/uavgrafana/data:/var/lib/grafana
      - ${USERDIR}/dockerha/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - influxdb
    labels:
      - "traefik.enable=false"


## Influxdb  - Time series database 
  influxdb:
    build:
      context: ${USERDIR}/dockerha/
      dockerfile: Dockerfile.influxdb
    container_name: influxdb
    domainname: ${DOMAINNAME}
    hostname: influxdb
#    restart: on-failure
#    ports:
#      - "8086:8086"
    volumes:
      - ${USERDIR}/dockerha/uavinfluxdb/data:/var/lib/influxdb
#      - ${USERDIR}/dockerha/uavinfluxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${USERDIR}/dockerha/shared:/shared
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - INFLUX_GRAPHITE_ENABLED=true
      - PRE_CREATE_DB=homeassistant
      - INFLUX_USER=${INFLUX_USER}
      - INFLUX_PASSWORD=${INFLUX_PASSWORD}
      - INFLUX_DB=${INFLUX_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_HADB=${INFLUXDB_HADB}
      - INFLUXDB_HAUSER=${INFLUXDB_HAUSER}
      - INFLUXDB_HAUSER_PASSWORD=${INFLUXDB_HAUSER_PASSWORD}
    networks:
      - ${NETWORK_NAME}
    labels:
      - "traefik.enable=false"


## Telegraf  - Influxdb agent
  telegraf:
    image: telegraf
    container_name: telegraf
    domainname: ${DOMAINNAME}
    hostname: telegraf
#    restart: on-failure
    volumes:
      - ${USERDIR}/dockerha/uavinfluxdb/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      - influxdb
    labels:
      - "traefik.enable=false"


networks:
  uavhanet:
    driver: overlay
