FROM grafana/grafana:4.4.2

RUN apt-get update && apt-get install -y curl gettext-base && rm -rf /var/lib/apt/lists/*

WORKDIR /etc/grafana

COPY ./uavgrafana/datasources ./datasources

RUN mkdir /app 

WORKDIR /app 

COPY ./shared/grafana-cmd.sh .

RUN chmod u+x grafana-cmd.sh

ENTRYPOINT ["sh", "/app/grafana-cmd.sh"]
